version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: e_shop_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - e_shop_data:/var/lib/postgresql/data

volumes:
  e_shop_data: