version: '3.8'
services:
  api:
    build: .
    container_name: e-shop-api
    ports:
      - "8001:8001"
    env_file:
      - .env
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./uploads:/app/uploads
      - ./certs:/app/certs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - e-shop-network

  db:
    image: postgres:15-alpine
    container_name: go-psql
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT:-5433}:5432"
    volumes:
      - e_shop_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - e-shop-network

  redis:
    image: redis:7-alpine
    container_name: go-redis
    ports:
      - "${REDIS_PORT:-6380}:6379"
    volumes:
      - go_redis_data:/data
    networks:
      - e-shop-network

volumes:
  e_shop_data:
  go_redis_data:

networks:
  e-shop-network: